"""Add Buyer model for marketplace

Revision ID: 199be9da0596
Revises: d506723d04d4
Create Date: 2025-12-08 02:21:49.114065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199be9da0596'
down_revision = 'd506723d04d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyers_email'), ['email'], unique=True)

    with op.batch_alter_table('buyer_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_buyer_offers_buyer_id_buyers', 'buyers', ['buyer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_offers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buyer_offers_buyer_id_buyers', type_='foreignkey')
        batch_op.drop_column('buyer_id')

    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyers_email'))

    op.drop_table('buyers')
    # ### end Alembic commands ###
