"""initial clean migration

Revision ID: 1a1f7a7a176f
Revises: 
Create Date: 2025-12-04 16:27:06.547803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1f7a7a176f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('caste_category', sa.String(length=50), nullable=True),
    sa.Column('caste_certificate_path', sa.String(length=255), nullable=True),
    sa.Column('is_physically_handicapped', sa.Boolean(), nullable=True),
    sa.Column('disability_certificate_path', sa.String(length=255), nullable=True),
    sa.Column('is_maharashtra_resident', sa.Boolean(), nullable=True),
    sa.Column('permanent_address', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('record_of_rights_7_12_path', sa.String(length=255), nullable=True),
    sa.Column('lease_deed_8a_path', sa.String(length=255), nullable=True),
    sa.Column('land_survey_numbers', sa.String(length=500), nullable=True),
    sa.Column('total_land_area_hectares', sa.Float(), nullable=False),
    sa.Column('land_area_gunthas', sa.Float(), nullable=True),
    sa.Column('land_holder_type', sa.String(length=50), nullable=True),
    sa.Column('owns_land_in_multiple_villages', sa.Boolean(), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('current_crops', sa.String(length=500), nullable=True),
    sa.Column('is_oilseed_farmer', sa.Boolean(), nullable=True),
    sa.Column('oilseed_enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('account_holder_name', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('income_certificate_path', sa.String(length=255), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('is_pm_kisan_beneficiary', sa.Boolean(), nullable=True),
    sa.Column('pm_kisan_reference_id', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=True),
    sa.Column('documents_verified', sa.Boolean(), nullable=True),
    sa.Column('irrigation_type', sa.String(length=50), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('land_unit', sa.String(length=20), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number')
    )
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmers_farmer_id'), ['farmer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_farmers_phone_number'), ['phone_number'], unique=True)

    op.create_table('market_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheme_type', sa.String(length=50), nullable=False),
    sa.Column('focus_area', sa.String(length=100), nullable=False),
    sa.Column('focus_color', sa.String(length=20), nullable=True),
    sa.Column('benefit_amount', sa.String(length=255), nullable=False),
    sa.Column('eligibility_criteria', sa.Text(), nullable=False),
    sa.Column('apply_steps', sa.Text(), nullable=True),
    sa.Column('external_link', sa.String(length=255), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schemes_scheme_code'), ['scheme_code'], unique=True)

    op.create_table('crop_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('photo1_path', sa.String(length=255), nullable=True),
    sa.Column('photo2_path', sa.String(length=255), nullable=True),
    sa.Column('photo3_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer_rewards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('points_from_switching', sa.Float(), nullable=True),
    sa.Column('points_from_soil_test', sa.Float(), nullable=True),
    sa.Column('points_from_sales', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('device_serial', sa.String(length=100), nullable=True),
    sa.Column('installed', sa.Boolean(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_serial')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('action_link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('mandi_name', sa.String(length=100), nullable=True),
    sa.Column('alert_price', sa.Float(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('harvest_date', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('farmer_name', sa.String(length=200), nullable=True),
    sa.Column('farmer_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('buyer_price', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subsidy_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('application_data', sa.Text(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('application_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_mobile', sa.String(length=20), nullable=True),
    sa.Column('buyer_location', sa.String(length=255), nullable=True),
    sa.Column('initial_price', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['crop_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sell_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['sell_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('light', sa.Float(), nullable=True),
    sa.Column('probe_temp', sa.Float(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('sell_photos')
    op.drop_table('buyer_offers')
    op.drop_table('subsidy_applications')
    op.drop_table('sell_requests')
    op.drop_table('price_alerts')
    op.drop_table('otp_records')
    op.drop_table('notifications')
    op.drop_table('iot_devices')
    op.drop_table('farmer_rewards')
    op.drop_table('device_requests')
    op.drop_table('crop_listings')
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schemes_scheme_code'))

    op.drop_table('schemes')
    op.drop_table('market_prices')
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmers_phone_number'))
        batch_op.drop_index(batch_op.f('ix_farmers_farmer_id'))

    op.drop_table('farmers')
    # ### end Alembic commands ###
