"""Add water_type field to Farmer model

Revision ID: 434f490538b0
Revises: 1a1f7a7a176f
Create Date: 2025-12-04 16:31:58.517935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434f490538b0'
down_revision = '1a1f7a7a176f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('irrigation_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('irrigation_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('water_type')

    # ### end Alembic commands ###
