"""Add real-time bidding system tables

Revision ID: 5b4b6fd4005b
Revises: ad6e05a92c6c
Create Date: 2025-12-09 06:40:34.768949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4b6fd4005b'
down_revision = 'ad6e05a92c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_quintal', sa.Float(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('min_bid_price', sa.Float(), nullable=False),
    sa.Column('current_highest_bid', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('winning_buyer_id', sa.String(length=36), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('photo1_path', sa.String(length=255), nullable=True),
    sa.Column('photo2_path', sa.String(length=255), nullable=True),
    sa.Column('photo3_path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['winning_buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=True),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('bid_type', sa.String(length=20), nullable=True),
    sa.Column('max_bid_amount', sa.Float(), nullable=True),
    sa.Column('auto_increment', sa.Float(), nullable=True),
    sa.Column('is_winning', sa.Boolean(), nullable=True),
    sa.Column('is_outbid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('outbid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auction_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('bid_id', sa.String(length=36), nullable=True),
    sa.Column('old_bid', sa.Float(), nullable=True),
    sa.Column('new_bid', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_market_prices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_market_prices',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('commodity_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('market_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('market_state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('market_district', sa.VARCHAR(length=100), nullable=True),
    sa.Column('open_price', sa.FLOAT(), nullable=True),
    sa.Column('high_price', sa.FLOAT(), nullable=True),
    sa.Column('low_price', sa.FLOAT(), nullable=True),
    sa.Column('close_price', sa.FLOAT(), nullable=True),
    sa.Column('trading_volume', sa.FLOAT(), nullable=True),
    sa.Column('price_date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bid_history')
    op.drop_table('transactions')
    op.drop_table('bids')
    op.drop_table('auction_notifications')
    op.drop_table('auctions')
    # ### end Alembic commands ###
