"""add market price model for commodity prices

Revision ID: ad6e05a92c6c
Revises: b4113f2f9d66
Create Date: 2025-12-09 02:03:44.175845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6e05a92c6c'
down_revision = 'b4113f2f9d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old market_prices table to recreate with new schema
    op.drop_table('market_prices')
    
    # Create new market_prices table with proper schema
    op.create_table(
        'market_prices',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('commodity_name', sa.String(100), nullable=False),
        sa.Column('market_name', sa.String(100), nullable=False),
        sa.Column('market_state', sa.String(50), nullable=True),
        sa.Column('market_district', sa.String(100), nullable=True),
        sa.Column('open_price', sa.Float(), nullable=True),
        sa.Column('high_price', sa.Float(), nullable=True),
        sa.Column('low_price', sa.Float(), nullable=True),
        sa.Column('close_price', sa.Float(), nullable=True),
        sa.Column('trading_volume', sa.Float(), nullable=True),
        sa.Column('price_date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('buyer_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('crop_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('distance_km', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('price_date')
        batch_op.drop_column('trading_volume')
        batch_op.drop_column('close_price')
        batch_op.drop_column('low_price')
        batch_op.drop_column('high_price')
        batch_op.drop_column('open_price')
        batch_op.drop_column('market_district')
        batch_op.drop_column('market_state')
        batch_op.drop_column('market_name')
        batch_op.drop_column('commodity_name')

    # ### end Alembic commands ###
