"""empty message

Revision ID: d506723d04d4
Revises: farmer_recommendations_001
Create Date: 2025-12-08 00:41:11.069372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd506723d04d4'
down_revision = 'farmer_recommendations_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sahayak_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sahayak_chats_created_at'))

    op.drop_table('sahayak_chats')
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('income_certificate_path')
        batch_op.drop_column('record_of_rights_7_12_path')
        batch_op.drop_column('lease_deed_8a_path')
        batch_op.drop_column('land_survey_numbers')
        batch_op.drop_column('documents_verified')
        batch_op.drop_column('caste_certificate_path')
        batch_op.drop_column('is_maharashtra_resident')
        batch_op.drop_column('disability_certificate_path')
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('account_holder_name')
        batch_op.drop_column('email')
        batch_op.drop_column('aadhaar_number')
        batch_op.drop_column('bank_branch')
        batch_op.drop_column('owns_land_in_multiple_villages')
        batch_op.drop_column('ifsc_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ifsc_code', sa.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('owns_land_in_multiple_villages', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('bank_branch', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_number', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('account_holder_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('disability_certificate_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_maharashtra_resident', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('caste_certificate_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('documents_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('land_survey_numbers', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('lease_deed_8a_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('record_of_rights_7_12_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('income_certificate_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True))

    op.create_table('sahayak_chats',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('farmer_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.Column('bot_response', sa.TEXT(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_emotion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('analysis_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sahayak_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sahayak_chats_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
