"""Add FarmerRecommendation model for storing AI recommendations

Revision ID: farmer_recommendations_001
Revises: 567f8c9a1b3d
Create Date: 2025-12-07 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'farmer_recommendations_001'
down_revision = '567f8c9a1b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('match_percentage', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_recommendations_created_at'), 'farmer_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_farmer_recommendations_farmer_id'), 'farmer_recommendations', ['farmer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmer_recommendations_farmer_id'), table_name='farmer_recommendations')
    op.drop_index(op.f('ix_farmer_recommendations_created_at'), table_name='farmer_recommendations')
    op.drop_table('farmer_recommendations')
    # ### end Alembic commands ###
