"""Add heat_index and soil_raw fields to sensor_readings.

Revision ID: iot_enhancements_002
Revises: iot_enhancements_001
Create Date: 2025-12-09

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'iot_enhancements_002'
down_revision = 'iot_enhancements_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heat_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('soil_raw', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_column('soil_raw')
        batch_op.drop_column('heat_index')

    # ### end Alembic commands ###
